added extra parameter to the SeQuant context which indetifies whether…
ValeevGroup/SeQuant2 pull request #55
Opened 2021-04-30 18:40 UTC by cmasteran1

… or not spin free or spin basis is used for fermions. Context affects the symmetry of operators and the printing labels to_latex()

2021-06-11 18:37 UTC, evaleev commented
@cmasteran1 just to make sure: this depends on #58 ?

2021-06-13 02:49 UTC, cmasteran1 commented
Yes those changes only make sense if the wick algorithm uses the tensor form

2021-06-14 02:54 UTC, evaleev requested changes

2021-06-14 02:54 UTC, evaleev commented on examples/uccf12/uccf12.cpp
> +    /*auto hr_comm = do_wick( ex<Constant>(2) * (h*r - r*h) );  // this assumes symmetrization includes 1/2
is this meant to be removed? Commented out code should be removed, unless used as documentation of something

2021-06-14 02:54 UTC, evaleev commented on examples/uccf12/uccf12.cpp
> +   simplify(result);
formatting seems off here and elsewhere ... do you not have auto-formatting ON in IDE?

2021-11-25 19:27 UTC, merged